=== youcef1712/pacman/PacMan 3/PacMan/xsd/PacMan.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.monjeu.com/jeuPacMan"
           xmlns:pc="http://www.monjeu.com/jeuPacMan"
           elementFormDefault="qualified">

    <!-- Élément racine Jeu -->
    <xs:element name="Jeu" type="pc:Jeu"/>
    <xs:complexType name="Jeu">
        <xs:sequence>
            <xs:element name="Carte" type="pc:Carte"/>
            <xs:element name="Pacman" type="pc:Pacman"/>
            <xs:element name="Ennemis" type="pc:Ennemis"/>
            <xs:element name="etatJeu" type="pc:EtatJeu"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Carte">
        <xs:sequence>
            <xs:element name="Ligne" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Pacman">
        <xs:sequence>
            <xs:element name="PositionX" type="xs:int"/>
            <xs:element name="PositionY" type="xs:int"/>
            <xs:element name="vitesse" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Ennemis">
        <xs:sequence>
            <xs:element name="Ennemi" type="pc:Ennemi" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Ennemi">
        <xs:sequence>
            <xs:element name="PositionX" type="xs:int"/>
            <xs:element name="PositionY" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="EtatJeu">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Formulaire"/>
            <xs:enumeration value="Menu"/>
            <xs:enumeration value="Jeu"/>
            <xs:enumeration value="Perdu"/>
            <xs:enumeration value="Gagne"/>
            <xs:enumeration value="Quitter"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== youcef1712/pacman/PacMan 3/PacMan/xml/PacMan.xml
<?xml version="1.0" encoding="utf-8"?>
<pc:Jeu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:pc="http://www.monjeu.com/jeuPacMan" xsi:schemaLocation="http://www.monjeu.com/jeuPacMan ../xsd/PacMan.xsd">
  <pc:Carte>
    <pc:Ligne>0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</pc:Ligne>
    <pc:Ligne>0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0</pc:Ligne>
    <pc:Ligne>0 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 0</pc:Ligne>
    <pc:Ligne>0 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 0</pc:Ligne>
    <pc:Ligne>0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0</pc:Ligne>
    <pc:Ligne>0 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 0</pc:Ligne>
    <pc:Ligne>0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0</pc:Ligne>
    <pc:Ligne>0 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 0</pc:Ligne>
    <pc:Ligne>0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0</pc:Ligne>
    <pc:Ligne>0 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 0</pc:Ligne>
    <pc:Ligne>0 1 1 0 0 0 1 1 1 1 1 0 0 0 1 1 0</pc:Ligne>
    <pc:Ligne>0 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 0</pc:Ligne>
    <pc:Ligne>0 1 0 0 0 0 1 1 1 1 1 0 0 0 0 1 0</pc:Ligne>
    <pc:Ligne>0 1 1 1 0 1 1 0 0 0 1 1 0 1 1 1 0</pc:Ligne>
    <pc:Ligne>0 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 0</pc:Ligne>
    <pc:Ligne>0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</pc:Ligne>
  </pc:Carte>
  <pc:Pacman>
    <pc:PositionX>8</pc:PositionX>
    <pc:PositionY>11</pc:PositionY>
    <pc:vitesse>5</pc:vitesse>
  </pc:Pacman>
  <pc:Ennemis>
    <pc:Ennemi>
      <pc:PositionX>1</pc:PositionX>
      <pc:PositionY>1</pc:PositionY>
    </pc:Ennemi>
    <pc:Ennemi>
      <pc:PositionX>13</pc:PositionX>
      <pc:PositionY>11</pc:PositionY>
    </pc:Ennemi>
    <pc:Ennemi>
      <pc:PositionX>13</pc:PositionX>
      <pc:PositionY>1</pc:PositionY>
    </pc:Ennemi>
    <pc:Ennemi>
      <pc:PositionX>7</pc:PositionX>
      <pc:PositionY>3</pc:PositionY>
    </pc:Ennemi>
  </pc:Ennemis>
  <pc:etatJeu>Perdu</pc:etatJeu>
</pc:Jeu>
